{% set name = "python-flatbuffers" %}
{% set pypi_name = "flatbuffers" %}
{% set version = "25.1.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: e24a34dcd9fb4e0ea8cc0fc8ef9c5cd61c9d21527a6d536967587a37a4ff9676

build:
  number: 0
  script: VERSION=v{{ version }} {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - flatbuffers
    - flatbuffers.builder
    - flatbuffers.table

about:
  home: https://google.github.io/flatbuffers/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python runtime library for use with the Flatbuffers serialization format.
  description: |
    FlatBuffers is an efficient cross platform serialization library for C++, C#, C, Go, Java, JavaScript, Lobster, Lua, TypeScript, PHP, Python, and Rust. It was originally created at Google for game development and other performance-critical applications. This package is the python runtime library. The flatc compiler is in the flatbuffers conda package.
  doc_url: https://google.github.io/flatbuffers/
  doc_source_url: https://github.com/google/flatbuffers/tree/master/docs
  dev_url: https://github.com/google/flatbuffers

extra:
  recipe-maintainers:
    - kalefranz
    - njzjz
    - xhochy
