{% set name = "python-flatbuffers" %}
{% set pypi_name = "flatbuffers" %}
{% set version = "23.5.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 9ea1144cac05ce5d86e2859f431c6cd5e66cd9c78c558317c7955fb8d4c78d89

build:
  number: 0
  script: VERSION=v{{ version }} {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - flatbuffers
    - flatbuffers.builder
    - flatbuffers.table

about:
  home: https://google.github.io/flatbuffers/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python runtime library for use with the Flatbuffers serialization format.
  description: |
    FlatBuffers is an efficient cross platform serialization library for C++, C#, C, Go, Java, JavaScript, Lobster, Lua, TypeScript, PHP, Python, and Rust. It was originally created at Google for game development and other performance-critical applications. This package is the python runtime library. The flatc compiler is in the flatbuffers conda package.
  doc_url: https://google.github.io/flatbuffers/
  doc_source_url: https://github.com/google/flatbuffers/tree/master/docs
  dev_url: https://github.com/google/flatbuffers

extra:
  recipe-maintainers:
    - kalefranz
    - njzjz
    - xhochy
